# Generated by Django 5.0.6 on 2024-09-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0002_cliente_cuit_cliente_nombre_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenreparacion',
            name='informe_cliente',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenreparacion',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=21.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='ordenreparacion',
            name='precio_mano_obra',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ordenreparacion',
            name='precio_repuestos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ordenreparacion',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
