# Generated by Django 5.0.6 on 2024-10-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0003_ordenreparacion_informe_cliente_ordenreparacion_iva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nombre_empresa',
            field=models.CharField(blank=True, choices=[(1, 'Nubicom'), (2, 'Strong'), (3, 'IDS'), (4, 'Enterprise')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='marca',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='modelo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='tipo',
            field=models.CharField(blank=True, choices=[(1, 'Desktop'), (2, 'Notebook'), (3, 'All in one'), (4, 'Impresora')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ordenreparacion',
            name='falla',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordenreparacion',
            name='iva',
            field=models.DecimalField(blank=True, decimal_places=2, default=21.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='ordenreparacion',
            name='precio_mano_obra',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ordenreparacion',
            name='precio_repuestos',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ordenreparacion',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
