# Generated by Django 5.0.6 on 2024-10-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0004_alter_cliente_nombre_empresa_alter_equipo_marca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenreparacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado'), ('entregado', 'Equipo entregado')], default='pendiente', max_length=20),
        ),
    ]
