# Generated by Django 5.0.6 on 2024-10-18 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0009_alter_cliente_nombre_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='particular',
        ),
    ]
