# Generated by Django 5.0.6 on 2024-10-24 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0010_remove_cliente_particular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenreparacion',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='taller.cliente'),
        ),
        migrations.AlterField(
            model_name='ordenreparacion',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='taller.equipo'),
        ),
    ]
