# Generated by Django 5.0.6 on 2024-07-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0016_alter_impresora_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='impresoraasignadas',
            name='Empresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='impresoraasignadas',
            name='Equipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='impresoraasignadas',
            name='Impresora',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
