# Generated by Django 5.0.6 on 2024-07-23 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0020_documentacion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impresora',
            name='Empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='systems.empresa'),
            preserve_default=False,
        ),
    ]
