# Generated by Django 5.0.6 on 2024-07-24 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0022_rename_empresa_impresora_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impresora',
            name='Sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='systems.sucursal'),
        ),
    ]
